Fix sub-venv
OCR-D/ocrd_all pull request #145
Opened 2020-08-13 09:01 UTC by bertsky

Fixes #140 
Fixes #144

2020-08-13 09:25 UTC, stweil commented on Makefile
> +$(shell echo will-cite | parallel --citation >/dev/null 2>&1; chown -R --reference=$(HOME) $(HOME)/.parallel)
This would break builds on macOS:

    usage: chown [-fhnv] [-R [-H | -L | -P]] owner[:group] file ...
           chown [-fhnv] [-R [-H | -L | -P]] :group file ...

2020-08-13 09:27 UTC, stweil commented on Makefile
> +	if type deactivate >/dev/null 2>&1; then deactivate; fi; $(PYTHON) -m venv $(VIRTUAL_ENV)
I'd prefer running `deactivate` just before entering a recursive `make`. Then we know that there exists `$(VIRTUAL_ENV)/bin/deactivate`.

2020-08-13 10:28 UTC, bertsky commented on Makefile
> +$(shell echo will-cite | parallel --citation >/dev/null 2>&1; chown -R --reference=$(HOME) $(HOME)/.parallel)
Damn it. But then ocrd_all **already** cannot work on macOS, because we use the same recipe in the `deps-ubuntu` recipe.

So perhaps (in both instances) we should use `chown -R $(stat --format "%u:%g" FILE) TARGETS`. Would that work on macOS?

2020-08-13 10:35 UTC, bertsky commented on Makefile
> +	if type deactivate >/dev/null 2>&1; then deactivate; fi; $(PYTHON) -m venv $(VIRTUAL_ENV)
> I'd prefer running `deactivate` just before entering a recursive `make`. Then we know that there exists `$(VIRTUAL_ENV)/bin/deactivate`.

There's no `$(VIRTUAL_ENV)/bin/deactivate` (it's only a function defined in `$(VIRTUAL_ENV)/bin/activate`). 

But you're right, we could (activate and) deactivate before entering recursive make. However, that would further complicate the recipes.

Is there any particular reason for not having `deactivate` up there that you had in mind?

2020-08-13 14:00 UTC, stweil commented on Makefile
> +$(shell echo will-cite | parallel --citation >/dev/null 2>&1; chown -R --reference=$(HOME) $(HOME)/.parallel)
> Damn it. But then ocrd_all **already** cannot work on macOS, because we use the same recipe in the `deps-ubuntu` recipe.

`deps-ubuntu` won't work and will never be needed for macOS for obvious reasons.

2020-08-13 14:01 UTC, stweil commented on Makefile
> +$(shell echo will-cite | parallel --citation >/dev/null 2>&1; chown -R --reference=$(HOME) $(HOME)/.parallel)
> So perhaps (in both instances) we should use `chown -R $(stat --format "%u:%g" FILE) TARGETS`. Would that work on macOS?

`stat --format` is not supported, but the short form `stat -f` works on macOS, too:

    usage: stat [-FlLnqrsx] [-f format] [-t timefmt] [file ...]

2020-08-13 14:03 UTC, stweil commented on Makefile
> +$(shell echo will-cite | parallel --citation >/dev/null 2>&1; chown -R --reference=$(HOME) $(HOME)/.parallel)
There remains the question whether it is okay to set "will cite" automatically in a script. As I already said my answer is no.

2020-08-13 14:05 UTC, bertsky commented on Makefile
> +$(shell echo will-cite | parallel --citation >/dev/null 2>&1; chown -R --reference=$(HOME) $(HOME)/.parallel)
> but the short form `stat -f` works on macOS, too:

That's inconsistent with GNU stat again, which uses `-c` as shorthand (`-f` is short for `--file-system`). 

What's the portable answer to this?

2020-08-13 14:11 UTC, stweil commented on Makefile
> +$(shell echo will-cite | parallel --citation >/dev/null 2>&1; chown -R `stat -c %u:%g $(HOME)` $(HOME)/.parallel)
Using backticks in shell scripts is deprecated.
And `stat -c` is unsupported on macOS.

2020-08-13 14:14 UTC, bertsky commented on Makefile
> +$(shell echo will-cite | parallel --citation >/dev/null 2>&1; chown -R `stat -c %u:%g $(HOME)` $(HOME)/.parallel)
> Using backticks in shell scripts is deprecated.

It's still POSIX though. And we are in a makefile, so backticks help avoid less readable `$$(...)` syntax.

> And `stat -c` is unsupported on macOS.

Let's keep discussing this in the original thread.

2020-08-13 14:22 UTC, bertsky commented on Makefile
> +$(shell echo will-cite | parallel --citation >/dev/null 2>&1; chown -R --reference=$(HOME) $(HOME)/.parallel)
> What's the portable answer to this?

Probably not using `stat` at all. How about `ls -ldn | { read perm size user group rest; echo $user:$group; }` – does _that_ work under BSD/macOS, too?

2020-08-13 14:24 UTC, bertsky commented on Makefile
> +$(shell echo will-cite | parallel --citation >/dev/null 2>&1; chown -R --reference=$(HOME) $(HOME)/.parallel)
> There remains the question whether it is okay to set "will cite" automatically in a script. As I already said my answer is no.

As I [already said in the respective thread](https://github.com/OCR-D/ocrd_all/issues/139#issuecomment-673408513) GPL's answer is _yes_, and fundamentally so.

2020-08-14 14:03 UTC, bertsky commented on Makefile
> +$(shell echo will-cite | parallel --citation >/dev/null 2>&1; chown -R --reference=$(HOME) $(HOME)/.parallel)
> Probably not using `stat` at all. How about `ls -ldn | { read perm size user group rest; echo $user:$group; }` – does _that_ work under BSD/macOS, too?

@stweil please have a look at the current, `ls` based replacement for `chown --reference` – does it work on macOS?

2020-08-15 12:11 UTC, kba commented on Makefile
> +	if type deactivate >/dev/null 2>&1; then deactivate; fi; $(PYTHON) -m venv $(VIRTUAL_ENV)
Since it's a shell function, only `type deactivate` will work. Couldn't we do that as part of the `ACTIVATE_VENV` variable:

```make
ACTIVATE_VENV = deactivate; $(VIRTUAL_ENV)/bin/activate
```
?

2020-08-15 12:13 UTC, kba commented on Makefile
> +	@echo will cite | parallel --citation >/dev/null 2>&1
I have no qualms about circumventing the (GPL-incompatible) change per se but I wonder whether it is easier to just instruct users to do `sudo rm -rf ~/.parallel;echo 'will cite'|parallel --citation` on their own?

2020-08-15 15:22 UTC, bertsky commented on Makefile
> +	if type deactivate >/dev/null 2>&1; then deactivate; fi; $(PYTHON) -m venv $(VIRTUAL_ENV)
> Couldn't we do that as part of the `ACTIVATE_VENV` variable:
> 
> ```makefile
> ACTIVATE_VENV = deactivate; $(VIRTUAL_ENV)/bin/activate
> ```
> 
> ?

No. For two reasons:
- we use `ACTIVATE_VENV` in a `source` context. You cannot source a literal command sequence, only a file.
- the problem arose with outside venvs already activate before running `make`, which would not be affected by this.

2020-08-17 18:11 UTC, bertsky commented on Makefile
> +	@echo will cite | parallel --citation >/dev/null 2>&1
Some people read documentation (more or less), some don't. Those users which use `deps-ubuntu` should get the best automatic solution. This does not rule out documentation of course, as I have [said before](https://github.com/OCR-D/ocrd_all/issues/140#issuecomment-671916924).

2020-08-17 18:14 UTC, bertsky commented
703735d will also fix #151 (in the sense of offering a way out of stale/inconsistent state of `~/.parallel/semaphores`; the original issue was duplicate of #140).

2020-08-17 18:17 UTC, bertsky commented
@stweil @kba (after CI shows green) can we merge this?

2020-08-17 18:25 UTC, stweil commented on Makefile
> +	if type deactivate >/dev/null 2>&1; then deactivate; fi; $(PYTHON) -m venv $(VIRTUAL_ENV)
Let me repeat my preference with a fixed argument:

I'd prefer running deactivate just before entering a recursive make. Then we know that we are able to activate and deactivate the parent venv, and `deactivate` runs in the correct context (not with a different value of `VIRTUAL_ENV`).

2020-08-17 18:36 UTC, stweil commented
> @stweil @kba (as soon as CI shows green) can we merge this?

This is again a pull request which mixes different fixes. That makes reviews and merging really difficult.

2020-08-17 18:51 UTC, bertsky commented on Makefile
> +	if type deactivate >/dev/null 2>&1; then deactivate; fi; $(PYTHON) -m venv $(VIRTUAL_ENV)
> I'd prefer running deactivate just before entering a recursive make.

The problem with that was it would require adding the `deactivate` check/call to every instance of recursive `MAKE` call, which makes the recipes less readable.

> Then we know that we are able to activate and deactivate the parent venv

What do you mean by that? (We never know for sure whether the parent venv actually _is_ active already until we look up the `deactivate` function.)

> and `deactivate` runs in the correct context (not with a different value of `VIRTUAL_ENV`).

Granted, that is a _potential_ problem. But venvs created by `virtualenv` and the `venv` module have so far never relied on `VIRTUAL_ENV` during `deactivate` (and why should they?) – on the contrary, they merely `unset VIRTUAL_ENV`.

2020-08-17 19:29 UTC, stweil commented on Makefile
> +	if type deactivate >/dev/null 2>&1; then deactivate; fi; $(PYTHON) -m venv $(VIRTUAL_ENV)
> What do you mean by that? (We never know for sure whether the parent venv actually _is_ active already until we look up the `deactivate` function.)

The top level make can activate its venv before running deactivate and the recursive make, no need to look up `deactivate` as it must the defined after `activate`.

2020-08-17 20:05 UTC, bertsky commented on Makefile
> +	if type deactivate >/dev/null 2>&1; then deactivate; fi; $(PYTHON) -m venv $(VIRTUAL_ENV)
> The top level make can activate its venv before running deactivate and the recursive make, no need to look up `deactivate` as it must the defined after `activate`. And like that it does not matter whether there was a venv activated outside of make.

Ah, so you refer to the `. $(ACTIVATE_VENV); deactivate` pattern. But there's nothing to learn from the fact that we can activate the parent venv at that point, because we just created it (successfully), or it was already active (in which case activation is a no-op).

So to sum up (in my view) the lasting arguments for deactivating before entering recursively:
- pro: would give up the assumption that `deactivate` will (continue to) work even after `VIRTUAL_ENV` has been reassigned
- con: bloats the rules of all modules which need sub-venvs

Example:
https://github.com/OCR-D/ocrd_all/blob/adb5209f95d0b1499ebc91de948f63bc498d4c38/Makefile#L207-L215

…would have to become…

```make
$(call multirule,$(OCRD_COR_ASV_ANN)): cor-asv-ann
ifeq (0,$(MAKELEVEL))
	. $(ACTIVATE_VENV) && deactivate && $(MAKE) -B -o $< $(notdir $(OCRD_COR_ASV_ANN))
	$(call delegate_venv,$(OCRD_COR_ASV_ANN))
$(OCRD_COR_ASV_ANN): VIRTUAL_ENV := $(SUB_VENV)/headless-tf1
else
	$(pip_install)
endif
endif
```

If only I knew a way to reduce the amount and complexity of the recursive invocation (makelevel check, conditional, target-specific variable override, call recursively, call canned recipe for shell script wrapper)... then the choice would be easier.

@kba what's your preference?

2020-08-17 20:34 UTC, stweil commented on Makefile
> +	if type deactivate >/dev/null 2>&1; then deactivate; fi; $(PYTHON) -m venv $(VIRTUAL_ENV)
It's always the same pattern, so maybe the modified line could be rewritten to be even smaller than the current code?

2020-08-17 20:38 UTC, stweil commented on Makefile
> +	if type deactivate >/dev/null 2>&1; then deactivate; fi; $(PYTHON) -m venv $(VIRTUAL_ENV)
Would this work?

    SUB_VENV_MAKE := . $(ACTIVATE_VENV) && deactivate && $(MAKE)
    [...]
    ifeq (0,$(MAKELEVEL))
        $(SUB_VENV_MAKE) -B -o $< $(notdir $(OCRD_COR_ASV_ANN))

2020-08-18 09:06 UTC, bertsky commented on Makefile
> +	if type deactivate >/dev/null 2>&1; then deactivate; fi; $(PYTHON) -m venv $(VIRTUAL_ENV)
> Would this work?
> 
> ```
> SUB_VENV_MAKE := . $(ACTIVATE_VENV) && deactivate && $(MAKE)
> [...]
> ifeq (0,$(MAKELEVEL))
>     $(SUB_VENV_MAKE) -B -o $< $(notdir $(OCRD_COR_ASV_ANN))
> ```

Yes, it would.

2020-08-18 09:14 UTC, bertsky commented on Makefile
> +	if type deactivate >/dev/null 2>&1; then deactivate; fi; $(PYTHON) -m venv $(VIRTUAL_ENV)
>     * would give up the assumption that `deactivate` will (continue to) work even after `VIRTUAL_ENV` has been reassigned

BTW, it's the other way round if we switch to deactivation before recursive call: We assume that `activate` will (continue to) work even after `activate` has been called already. (The `virtualenv` and `venv` implementations both internally run `deactivate nondestructive` as a first step, so this does work.) Not that I recommend against it – just saying that we merely trade one assumption on future venv implementation details with another.

2020-08-18 09:49 UTC, kba commented on Makefile
> +	if type deactivate >/dev/null 2>&1; then deactivate; fi; $(PYTHON) -m venv $(VIRTUAL_ENV)
> Would this work?
> 
> ```
> SUB_VENV_MAKE := . $(ACTIVATE_VENV) && deactivate && $(MAKE)
> [...]
> ifeq (0,$(MAKELEVEL))
>     $(SUB_VENV_MAKE) -B -o $< $(notdir $(OCRD_COR_ASV_ANN))
> ```

That would be a good compromise IMHO.

2020-08-18 10:19 UTC, bertsky commented on Makefile
> +	if type deactivate >/dev/null 2>&1; then deactivate; fi; $(PYTHON) -m venv $(VIRTUAL_ENV)
> That would be a good compromise IMHO.

But is it worth the change? Mind you:

> just saying that we merely trade one assumption on future venv implementation details with another.

We are not gaining anything AFAICS, but sacrifice some comprehensibility in our rules. 

Unless there are still other, new arguments?

2020-08-18 10:24 UTC, kba commented on Makefile
> +	if type deactivate >/dev/null 2>&1; then deactivate; fi; $(PYTHON) -m venv $(VIRTUAL_ENV)
The original intention with the `deactivate` call at this point in the makefile was to fix https://github.com/OCR-D/ocrd_all/issues/144, right? What issue doees the deactivate/activate dance for recursive $(MAKE) calls fix? I have no problem with adding a bit of complexity in the, rather formulaic anyway, recursive recipes if that prevents future problems but IIUC @bertsky that wouldn't be the case here.

2020-08-18 10:26 UTC, kba commented on Makefile
> +	@chown -R `ls -ldn $(CURDIR) | { read perm size user group rest; echo $$user:$$group; }` .git $^
Should we set `SHELL = /bin/bash` to make sure this works across platforms?

2020-08-18 10:33 UTC, bertsky commented on Makefile
> +	if type deactivate >/dev/null 2>&1; then deactivate; fi; $(PYTHON) -m venv $(VIRTUAL_ENV)
> The original intention with the `deactivate` call at this point in the makefile was to fix #144, right?

Correct. But then @stweil argued that it would be even better to deactivate _before_ entering the recursive make. Both solutions _work_ currently, so this is largely a discussion about which might not under unknown, changed circumstances.

I have presented the analysis that _some_ assumptions on venv's `activate` or `deactivate` implementation are necessary either way.

> if that prevents future problems but IIUC @bertsky that wouldn't be the case here.

Exactly – it just trades one possible future problem with another, similar one.

2020-08-18 10:37 UTC, bertsky commented on Makefile
> +	@chown -R `ls -ldn $(CURDIR) | { read perm size user group rest; echo $$user:$$group; }` .git $^
I don't see bashisms here. But maybe there are elsewhere. On the other hand, we would have detected this, because bash behaves like POSIX sh when called as such by make (which is the default).

2020-08-18 11:13 UTC, kba commented on Makefile
> +	@chown -R `ls -ldn $(CURDIR) | { read perm size user group rest; echo $$user:$$group; }` .git $^
I thought the `{ .. }` construct wasn't POSIX sh, I stand corrected.

2020-08-18 13:00 UTC, stweil commented on Makefile
> +	@echo will cite | parallel --citation >/dev/null 2>&1
I disagree with this solution because I think it is not the right one. Citing the [GNU parallel FAQ](https://git.savannah.gnu.org/cgit/parallel.git/tree/doc/citation-notice-faq.txt):

    > Do automated scripts break if the notice is not silenced?

    No. Not a single time has that happened. This is due to the notice
    only being printed, if the output is to the screen - not if the output
    is to a file or a pipe.

So the message can just be ignored, or it could be sent to `/dev/null`.

2020-08-18 13:21 UTC, stweil commented on Makefile
> +	if type deactivate >/dev/null 2>&1; then deactivate; fi; $(PYTHON) -m venv $(VIRTUAL_ENV)
> The original intention with the deactivate call at this point in the makefile was to fix #144, right?

Good point. Why don't I get the issue described in #144? Up to now, I never missed the deactivate call, although I mostly run `make all` with an activated venv.

2020-08-18 13:23 UTC, stweil commented on Makefile
> +
That part is not needed with the alternate solutions for the citation issue.

2020-08-18 13:30 UTC, bertsky commented on Makefile
> +	@echo will cite | parallel --citation >/dev/null 2>&1
> I disagree with this solution because I think it is not the right one. Citing the [GNU parallel FAQ](https://git.savannah.gnu.org/cgit/parallel.git/tree/doc/citation-notice-faq.txt):
> 
> ```
> > Do automated scripts break if the notice is not silenced?
> 
> No. Not a single time has that happened. This is due to the notice
> only being printed, if the output is to the screen - not if the output
> is to a file or a pipe.
> ```
> 
> So the message can just be ignored, or it could be sent to `/dev/null`.

Let's untangle again:
```
parallel: Warning: Semaphore stuck for 30 seconds. Consider using --semaphoretimeout.
```
This was our failure in #140. It turned out to be caused by `~/.parallel` being created with sudo permissions (and subsequently using it in non-priviledged context).
We then not only fixed the permissions in a follow-up line, but addressed the problem with the citation notices, which just confuse users.
We did not want to suppress output in general, only the notice specifically.

2020-08-18 13:31 UTC, stweil commented on Makefile
> +	if type deactivate >/dev/null 2>&1; then deactivate; fi; $(PYTHON) -m venv $(VIRTUAL_ENV)
> We assume that activate will (continue to) work even after activate has been called already.

We already activate our venv without checking whether a venv was activated before, so that is a common practice.

2020-08-18 13:33 UTC, bertsky commented on Makefile
> +	@echo will cite | parallel --citation >/dev/null 2>&1
But yes, the (undocumented) solution `--no-notice` which you [dug up](https://github.com/OCR-D/ocrd_all/pull/155#issuecomment-675472138) would be even better!

2020-08-18 13:33 UTC, bertsky commented on Makefile
> +	@echo will cite | parallel --citation >/dev/null 2>&1
(Or, it turns out, just `--nn`)

2020-08-18 13:36 UTC, bertsky commented on Makefile
> +
The `chown` part is needed independent of the citation warning (see above). So let's use a variable `SEM` encapsulating  `sem --nn --fg --id ocrd_all_git` (as requested by @kba), but keep the last line in `deps-ubuntu` (as we don't know whether or not `sudo` sets `HOME` or not in the host's configuration).

2020-08-18 13:40 UTC, stweil commented on Makefile
> +
I only was speaking about the `chown` part for `$(HOME)/.parallel`.

2020-08-18 13:44 UTC, stweil commented on Makefile
> +
Ah, sorry, my fault. Yes, that part is still required because not only `will-cite` is written there but also the semaphore information.

2020-08-18 13:49 UTC, bertsky commented on Makefile
> +	if type deactivate >/dev/null 2>&1; then deactivate; fi; $(PYTHON) -m venv $(VIRTUAL_ENV)
> Why don't I get the issue described in #144? Up to now, I never missed the deactivate call, although I mostly run `make all` with an activated venv.

So, as I've said, I cannot reproduce it myself anymore. I'll drop this and rebase the PR.

2020-08-18 14:19 UTC, stweil commented on Makefile
> +	-$(RM) -r $(VIRTUAL_ENV)/build/tesseract
This change is not needed.

2020-08-18 14:20 UTC, stweil commented on Makefile
> +	@chown -R `ls -ldn $(CURDIR) | { read perm size user group rest; echo $$user:$$group; }` .git $^
This change is not needed.

2020-08-18 14:21 UTC, stweil commented on Makefile
> +	@chown -R `ls -ldn $(HOME) | { read perm size user group rest; echo $$user:$$group; }` $(HOME)/.parallel
As we are running on Debian or Ubuntu, the shorter old syntax could also be used. I'd prefer that because it is better readable.

2020-08-18 14:25 UTC, stweil commented on Makefile
> +	-git submodule deinit --all # --force
Why do you want to ignore errors here? Wouldn't it be better to fail if the `deinit`target cannot deinit all submodules?

2020-08-18 14:32 UTC, bertsky commented on Makefile
> +	@chown -R `ls -ldn $(CURDIR) | { read perm size user group rest; echo $$user:$$group; }` .git $^
> This change is not needed.

You mean because non-Ubuntu users won't call this anyway?

2020-08-18 14:35 UTC, bertsky commented on Makefile
> +	-git submodule deinit --all # --force
Because not all modules might be checked out (initialized) before. git will still return an error in that case.

2020-08-18 14:36 UTC, bertsky commented on Makefile
> +	-$(RM) -r $(VIRTUAL_ENV)/build/tesseract
It is: `make clean` (which depends on `clean-tesseract`) should work, regardless of whether Tesseract has already been built. This is common practice. (No-one expects `clean` to fail if there was nothing to clean.)

2020-08-18 14:38 UTC, stweil commented on Makefile
> +	@chown -R `ls -ldn $(CURDIR) | { read perm size user group rest; echo $$user:$$group; }` .git $^
Well, I call it on Debian, too, from time to time.

I just expect that any host which provides `apt-get` also has a recent `chown`. And running `make deps-ubuntu` without `apt-get` (for example on macOS) will fail anyway. It does not matter whether it fails here or some lines later, does it?

2020-08-18 14:41 UTC, stweil commented on Makefile
> +	-git submodule deinit --all # --force
I cannot confirm that. Deinit only fails for me when a submodule has modified contents, and for that case that's the desired behaviour.

2020-08-18 14:43 UTC, stweil commented on Makefile
> +	-$(RM) -r $(VIRTUAL_ENV)/build/tesseract
The old code does not fail for me. As long as `RM` is defined to be `rm -f` I would be surprised if it failed for you.

2020-08-18 14:45 UTC, stweil commented on Dockerfile
> +RUN sed -i 's/rights="none"/rights="read|write"/g' /etc/ImageMagick-6/policy.xml || true
```suggestion
RUN test -f /etc/ImageMagick-6/policy.xml && sed -i 's/rights="none"/rights="read|write"/g' /etc/ImageMagick-6/policy.xml
```

2020-08-18 14:47 UTC, stweil commented on Dockerfile
> +RUN sed -i 's/rights="none"/rights="read|write"/g' /etc/ImageMagick-6/policy.xml || true
Otherwise unexpected errors from `sed` would not be noticed.

2020-08-18 14:47 UTC, stweil commented on Dockerfile
> +RUN sed -i 's/name="disk" value="1GiB"/name="disk" value="8GiB"/g' /etc/ImageMagick-6/policy.xml || true
Dto.

2020-08-18 14:49 UTC, stweil commented on Makefile
> +	-$(RM) -r $(SUB_VENV)/*
No need to ignore errors from `$(RM)` which usually is `rm -f` and does not fail if there is nothing to remove.

2020-08-19 10:02 UTC, stweil commented on Makefile
> +	-$(MAKE) -C ocrd_olena clean-olena BUILD_DIR=$(VIRTUAL_ENV)/build/ocrd_olena
```suggestion
	test ! -f ocrd_olena/Makefile || \
	$(MAKE) -C ocrd_olena clean-olena BUILD_DIR=$(VIRTUAL_ENV)/build/ocrd_olena
```

2020-08-19 10:03 UTC, stweil commented on Makefile
> +	-$(RM) -r $(VIRTUAL_ENV)/build/tesseract
```suggestion
	$(RM) -r $(VIRTUAL_ENV)/build/tesseract
```

2020-08-19 10:04 UTC, stweil commented on Makefile
> +	-git submodule status | while read stat dir ver; do rmdir $$dir; done
Do you have a test case which requires this modification?

2020-08-19 10:11 UTC, stweil requested changes
Please update the PR to make it ready for merging:

- Update my commits from PR #153 to fix a misplaced argument and to fix Circle CI.
- Don't ignore failing commands. Some of the related changes are not needed, and for others it is better to improve the command than to ignore errors.
- Use the old `chown` variant for `deps-ubuntu` because portability it not an issue for that target and the old variant is shorter and better readable.

2020-08-19 11:02 UTC, bertsky commented on Makefile
> +	-git submodule deinit --all # --force
Yeah, I agree `deinit` should fail under these conditions.

2020-08-19 11:04 UTC, bertsky commented on Dockerfile
> +RUN sed -i 's/rights="none"/rights="read|write"/g' /etc/ImageMagick-6/policy.xml || true
> Otherwise unexpected errors from `sed` would not be noticed.

Which errors do you expect? The _only_ thing that can go wrong here is if the file is not present, or not readable/writable – all of which is covered by the original change. It's also more concise, showing that this step should never break the build.

2020-08-19 11:14 UTC, bertsky commented on Makefile
> +	-$(RM) -r $(SUB_VENV)/*
> No need to ignore errors from `$(RM)` which usually is `rm -f` and does not fail if there is nothing to remove.

Not if you simply don't have the necessary priviledges. But you might argue that it _does_ make sense to let `clean` fail under these circumstances.

2020-08-19 11:25 UTC, stweil commented on Makefile
> +	-$(RM) -r $(SUB_VENV)/*
When I run `make clean`, I expect a certain outcome, namely a defined set of files which is ready for a fresh build. So yes, `make clean` should fail if it is not able to do that.

2020-08-19 11:31 UTC, stweil commented on Dockerfile
> +RUN sed -i 's/rights="none"/rights="read|write"/g' /etc/ImageMagick-6/policy.xml || true
The only acceptable condition is that the file is missing. Then there is no need to patch it of course.

If there is a problem with access permissions, that's a problem which should abort the process, because the code here fails to patch the file although that is required.

If it does not matter whether the existing file is patched or not, I suggest to remove the whole line.

2020-08-19 12:25 UTC, kba commented on Makefile
> +	-$(RM) -r $(VIRTUAL_ENV)/build/tesseract
It's not necessary to ignore errors from `rm -rf` because it will virtually never throw one. But it doesn't hurt either, making clear the intent to "remove no matter what" which fits the target.

2020-08-19 12:26 UTC, kba commented on Makefile
> +	@chown -R `ls -ldn $(CURDIR) | { read perm size user group rest; echo $$user:$$group; }` .git $^
Since the target is ubuntu/debian specific, a portable solution, though meritful per se, is not sensible here. Unless there's a reason beyond portability for the new construct.

2020-08-19 12:30 UTC, kba commented on Dockerfile
> +RUN sed -i 's/rights="none"/rights="read|write"/g' /etc/ImageMagick-6/policy.xml || true
> 
> 
> > Otherwise unexpected errors from `sed` would not be noticed.
> 
> Which errors do you expect? The _only_ thing that can go wrong here is if the file is not present, or not readable/writable – all of which is covered by the original change. It's also more concise, showing that this step should never break the build.

Why would the file not be present in the Docker image? We know exactly which base image we build upon, so we can be sure whether the image magick config files exist. If they do not, because the image changed e.g., then we should probably take notice by the build failing. So unless I overlook something, I'm against hiding such errors.

2020-08-19 15:09 UTC, bertsky commented on Dockerfile
> +RUN sed -i 's/rights="none"/rights="read|write"/g' /etc/ImageMagick-6/policy.xml || true
> Why would the file not be present in the Docker image? We know exactly which base image we build upon, so we can be sure whether the image magick config files exist. If they do not, because the image changed e.g., then we should probably take notice by the build failing. So unless I overlook something, I'm against hiding such errors.

Because not all module selections depend on IM. For example, if you exclude `ocrd_olena`, Docker will probably not have ImageMagick. (That Dockerfile is not only used for pre-built configs!)

2020-08-19 15:18 UTC, kba commented on Dockerfile
> +RUN sed -i 's/rights="none"/rights="read|write"/g' /etc/ImageMagick-6/policy.xml || true
Oh right, hadn't thought of that. Then `|| true` in those statements makes sense.

2020-08-19 16:28 UTC, bertsky commented on Dockerfile
> +RUN sed -i 's/rights="none"/rights="read|write"/g' /etc/ImageMagick-6/policy.xml || true
> The only acceptable condition is that the file is missing. Then there is no need to patch it of course.

This is the case (see above)

> If there is a problem with access permissions, that's a problem which should abort the process, because the code here fails to patch the file although that is required.

Agreed, but in our Docker build we are always priviledged, so this is actually out.

> If it does not matter whether the existing file is patched or not, I suggest to remove the whole line.

It does – IM (even the library) does not work otherwise, due to the overly restrictive defaults. (And I think IM's policy workaround to a security problem is a bad design choice...)

2020-08-19 16:36 UTC, kba commented
> * Update my commits from PR #153 to fix a misplaced argument and to fix Circle CI.

CI passes.

> * Don't ignore failing commands. Some of the related changes are not needed, and for others it is better to improve the command than to ignore errors.

This has been resolved. ("Because not all module selections depend on IM. For example, if you exclude ocrd_olena, Docker will probably not have ImageMagick. (That Dockerfile is not only used for pre-built configs!)")

> 
> * Use the old `chown` variant for `deps-ubuntu` because portability it not an issue for that target and the old variant is shorter and better readable.

Done

> 
> * Please consider also my suggestions for the `Dockerfile` changes.

Done (see above)

So @stweil @bertsky anything missing or can we merge?

2020-08-19 16:43 UTC, stweil requested changes

2020-08-19 16:43 UTC, stweil commented on Makefile
> +	@chown -R --reference=$(CURDIR) .git $^
@bertsky, why do you want to hide the `chown` commands in the build output?

2020-08-19 16:43 UTC, stweil commented on Makefile
> +	-$(MAKE) -C ocrd_olena clean-olena BUILD_DIR=$(VIRTUAL_ENV)/build/ocrd_olena
Still unresolved ...

2020-08-19 16:45 UTC, kba commented on Makefile
> +	@chown -R --reference=$(CURDIR) .git $^
Yes, let's keep those for debugging build.log.

2020-08-19 17:02 UTC, bertsky commented on Makefile
> +	-$(MAKE) -C ocrd_olena clean-olena BUILD_DIR=$(VIRTUAL_ENV)/build/ocrd_olena
The problem still is that if `clean-olena` fails, then `clean` would not happen. IMO by convention the semantics of `clean` never includes a notion of success, only _try to remove anything that might be in the way_.

2020-08-19 17:07 UTC, bertsky commented on Makefile
> +	@chown -R --reference=$(CURDIR) .git $^
done.

2020-08-19 17:08 UTC, bertsky commented
> anything missing or can we merge?

There's still a similar problem for [wget](https://github.com/OCR-D/ocrd_all/pull/153#discussion_r473116099)

2020-08-19 17:44 UTC, stweil commented on Makefile
> +	-$(MAKE) -C ocrd_olena clean-olena BUILD_DIR=$(VIRTUAL_ENV)/build/ocrd_olena
Then please let us wait until such a failure occurs. Do you have some reference for the convention which I did not know?

2020-08-19 17:51 UTC, stweil commented on README.md
> +Tange, Ole: GNU Parallel 20200722 ('Privacy Shield'). July 2020. https://doi.org/10.5281/zenodo.3956817
That's not the latest version. The newer one is better.

2020-08-19 18:41 UTC, bertsky commented
Wow.

> [must replace which with command -v in Bourne sh](/OCR-D/ocrd_all/pull/145/commits/94040ca8bc96723feaae8be1e17553bd06b52a08)

This is yet another portability nightmare. We [apparently](https://github.com/OCR-D/ocrd_all/runs/1004210143) cannot rely on `which`, because some cache does not get updated soon enough after `apt install`. Also, they say `which` is actually from old csh, and has never been standardized. The proper way for Bourne shells or POSIX sh is said to be `command -v`, but bash _in POSIX mode_ offers [neither](https://github.com/OCR-D/ocrd_all/runs/1004274175) `command` nor `type`, which is stunning. That aspect is not even covered by this (otherwise exhaustive) [SO thread](https://unix.stackexchange.com/questions/85249/why-not-use-which-what-to-use-then) on the subject.

Now what do we do? Crawl out and beg for `SHELL = /usr/bin/env bash` (using `command -v`), or find another tool, or debug the [cache problem](https://github.com/OCR-D/ocrd_all/runs/1004210143)?

2020-08-19 19:07 UTC, bertsky commented
> This is yet another portability nightmare. We [apparently](https://github.com/OCR-D/ocrd_all/runs/1004210143) cannot rely on `which`, because some cache does not get updated soon enough after `apt install`. Also, they say `which` is actually from old csh, and has never been standardized. The proper way for Bourne shells or POSIX sh is said to be `command -v`, but bash _in POSIX mode_ offers [neither](https://github.com/OCR-D/ocrd_all/runs/1004274175) `command` nor `type`, which is stunning. That aspect is not even covered by this (otherwise exhaustive) [SO thread](https://unix.stackexchange.com/questions/85249/why-not-use-which-what-to-use-then) on the subject.
> 
> Now what do we do? Crawl out and beg for `SHELL = /usr/bin/env bash` (using `command -v`), or find another tool, or debug the [cache problem](https://github.com/OCR-D/ocrd_all/runs/1004210143)?

Oh, got it: For one, `/bin/sh` is not bash on Debian, but dash. But more importantly, `make` itself (regardless of whether via `shell` function or recipe) will decide for itself _not_ to invoke a shell, but search the executable in PATH, if it sees only one instruction. Thus, builtins like `command` don't work.

2020-08-20 09:00 UTC, stweil commented
> Thus, builtins like command don't work.

Well, `command` works for me without a hack, see this `Makefile`:

    TEST := $(shell command -v make)
    all:
    	@echo test=$(TEST)

How did you get a different result? If it works for you, too, I suggest to remove all hacks again.

And there is no cache problem with `which`.

2020-08-20 09:27 UTC, stweil commented
@bertsky, I now merged most of your commits, especially the urgent bug fixes. Please rebase your PR, so we can discuss the remaining ones easier.

2020-08-20 09:28 UTC, bertsky commented
> Well, `command` works for me without a hack, see this `Makefile`:
> 
> ```
> TEST := $(shell command -v make)
> all:
> 	@echo test=$(TEST)
> ```
> 
> How did you get a different result?

You didn't say what your result was ;-)
With `make` version 4.1, I get:
```
make: command: Command not found
test=
```
But if I add a semicolon to the end of the `shell` call, then this becomes:
```
test=/usr/bin/make
```

Anyway, we don't need any `which` or `command` test, we can just `$(shell PROG --version)`. 

Meanwhile, I have also found the actual reason why our `$(error ...)` calls were all evaluated out of context: `.EXPORT_ALL_VARIABLES` breaks the usual expansion conditions of course. So removing this and using `export VIRTUAL_ENV` fixes all our wget/sem problems during `deps-ubuntu`. 

It's even possible to run `deps-ubuntu` without having `git` before now (as the README already claimed).

2020-08-20 09:31 UTC, bertsky commented
> I now merged most of your commits, especially the urgent bug fixes. Please rebase your PR, so we can discuss the remaining ones easier.

What the ...

2020-08-20 09:38 UTC, bertsky commented
> > I now merged most of your commits, especially the urgent bug fixes. Please rebase your PR, so we can discuss the remaining ones easier.
> 
> What the ...

@stweil you must be joking! You made me undo most of my PR after 3 days back and forth, and then just before I finally come around fixing the last issues, you just drag the commits out of the PR without even asking? I just reset master to the previous state, so we can wait for CI in the _current, fixed_ state here and _then_ merge if everyone is satisfied (as it should be).

2020-08-20 09:44 UTC, kba commented
> @bertsky, I now merged most of your commits, especially the urgent bug fixes. Please rebase your PR, so we can discuss the remaining ones easier.

@stweil why did you do that? We were close to finishing the discussions, weren't we?

2020-08-20 09:51 UTC, stweil commented
> why did you do that

I had the impression that it was time to fix some issues after a whole week of discussion. So I applied those patches where we agreed that they are fine.

What is the problem with this? Rebasing @bertsky's remaining commits is easy. I have already done in locally and could push that state to a new branch if that helps.

2020-08-20 09:56 UTC, bertsky commented on README.md
> +Tange, Ole: GNU Parallel 20200722 ('Privacy Shield'). July 2020. https://doi.org/10.5281/zenodo.3956817
So all I need is adding https://github.com/OCR-D/ocrd_all/pull/153/commits/635068e9fba6f341df47b7cedeefbd3e2f4d0410 right?

2020-08-20 09:59 UTC, stweil commented on README.md
> +Tange, Ole: GNU Parallel 20200722 ('Privacy Shield'). July 2020. https://doi.org/10.5281/zenodo.3956817
I already added the reference to latest git, so you can remove that commit from your branch.

2020-08-20 09:59 UTC, kba commented
> > why did you do that
> 
> I had the impression that it was time to fix some issues after a whole week of discussion. So I applied those patches where we agreed that they are fine.

We are all eager for a fix, but it should be based on consensus and successful CI. Cherry-picking individual commits and pushing them to master without consultation is just not good practice. We all have the power to push to master but we should only use it once we're in agreement. We were close but not yet there.

> 
> What is the problem with this? Rebasing @bertsky's remaining commits is easy. I have already done in locally and could push that state to a new branch if that helps.

Again, it's not a question of technicality but of courtesy. And you are - rightly - an adherent of concise pull requests and static code analysis. Cherry-picking from an almost finished PR with 90+ discussion threads without asking first here or in gitter is not good. I appreciate that the pace of discussions can sometimes be frustrating but finding consensus improves the product in the long-term.

2020-08-20 10:28 UTC, kba commented on README.md
> +Tange, Ole: GNU Parallel 20200722 ('Privacy Shield'). July 2020. https://doi.org/10.5281/zenodo.3956817
https://github.com/OCR-D/ocrd_all/pull/145/commits/7a57df7b3fba53e218a395b4d1e28f06dc28d519

2020-08-20 10:31 UTC, kba commented
CI succeeded, the last commit only adapted the parallel citation in the README, which will not break building. So thanks a lot @bertsky and @stweil for the continued effort!

2020-08-20 10:31 UTC, merged

2020-08-20 12:28 UTC, bertsky commented
> What is the problem with this? Rebasing @bertsky's remaining commits is easy. I have already done in locally and could push that state to a new branch if that helps.

@stweil Also, you forget that rebasing then becomes much harder and a one-way direction. In this concrete case, I had already rebased this PR locally, fixing the early commits regarding the sem and wget failures (which you yourself have been pointing out mostly). We were in the middle of a discussion about these. By dragging them onto master directly, you made it impossible to edit/undo/reorder them. After all, that's what a PR is for: aggregating a set of mutually supporting/consistent commits that have to be considered and developed together until mature enough to integrate at once.