Report missing sem instead of failing with error
OCR-D/ocrd_all pull request #153
Opened 2020-08-17 19:43 UTC by stweil

Signed-off-by: Stefan Weil <sw@weilnetz.de>

2020-08-17 19:47 UTC, stweil commented
PR #145 includes a different solution.

The current PR can be extended to work without `sem` (for example for non-parallel make) or with an alternative semaphore implementation.

2020-08-18 11:16 UTC, kba commented
I like introducing `$(SEM)` to replace the call, c.f. https://github.com/OCR-D/ocrd_all/pull/149. But I'd prefer it if we agreed on #145.

2020-08-18 13:54 UTC, stweil commented
@bertsky, please review. If this PR is okay for you, I suggest to rebase your PR #145 after this one was merged.

2020-08-18 13:56 UTC, stweil commented
@kba, I added a commit which fixes the citation issue, so please review.

2020-08-18 13:57 UTC, stweil commented
Regarding the GNU parallel citation issue, there remains the question how to respect it. I suggest to add the citation to the README.md here or to the OCR-D website. Which variant is preferred?

2020-08-18 14:00 UTC, bertsky commented
> please review. If this PR is okay for you, I suggest to rebase your PR #145 after this one was merged.

Good idea to combine with the `error`. But I am against merging this alone, because (as you see) CI fails here. #145 has a different solution for that. So I'll just cherry-pick your 2 commits here and continue rebasing #145 (so let's see if CI agrees with all that).

2020-08-18 14:17 UTC, bertsky commented
> and then let's add the citation GNU parallel's authors crave to the Readme

ok, just what section were you thinking of? Below the link to contributing.md perhaps?

2020-08-18 14:28 UTC, bertsky commented
> > please review. If this PR is okay for you, I suggest to rebase your PR #145 after this one was merged.
> 
> Good idea to combine with the `error`

Damnit. No, now I remember there was a good reason _not_ to include the `error` function into the `sem` call unconditionally. I already had this correct in my branch... (get a feeling I am working backwards all day)

2020-08-18 22:33 UTC, bertsky requested changes

2020-08-18 22:33 UTC, bertsky commented on Makefile
> +$(if $(shell which sem),sem --fg --id --nn ocrd_all_git ,$(error "Please install GNU parallel"))
BTW, this does not work. You placed `--nn` between `--id` and the identifier.

But CI also shows this does not work in general. For some reason (I just cannot seem to remember it) the canned recipe gets evaluated even outside of its usage, right in the middle of `custom-deps-ubuntu`. It's probably a `make` bug. In my solution I ended placing the `error` function into the semaphore recipe directly.

2020-08-19 05:06 UTC, stweil commented on Makefile
> +$(if $(shell which sem),sem --fg --id --nn ocrd_all_git ,$(error "Please install GNU parallel"))
Ah, sorry. I updated the PR with the right order of the `sem` arguments and will investigate the CI error.

2020-08-19 05:33 UTC, stweil commented on Makefile
> +$(if $(shell which sem),sem --fg --id --nn ocrd_all_git ,$(error "Please install GNU parallel"))
@bertsky, the CI problem is caused by `make deps-ubuntu` which fails when GNU parallel is missing. Either we must require an installation of GNU parallel before using `make` with ocrd_all, or we must disable lines 33 and 34 in `Makefile` if the target is `deps-ubuntu`.

2020-08-19 05:40 UTC, stweil commented on Makefile
> +$(if $(shell which sem),sem --fg --id --nn ocrd_all_git ,$(error "Please install GNU parallel"))
CI should be fixed now.

2020-08-19 09:53 UTC, stweil commented
@bertsky, @kba, do you suggest more modifications? CI is fixed now, and I think this PR should be applied (and PR #145 rebased then).

2020-08-19 12:08 UTC, stweil commented
I now enhanced `README.md` with a reference for GNU parallel, see https://github.com/stweil/ocrd_all/tree/doc#acknowledgments.

2020-08-19 14:25 UTC, bertsky commented on Makefile
> +$(if $(shell which sem),sem --fg --id --nn ocrd_all_git ,$(error "Please install GNU parallel"))
> the CI problem is caused by `make deps-ubuntu` which fails when GNU parallel is missing.

That's what I've just said.

>  Either we must require an installation of GNU parallel before using `make` with ocrd_all, or we must disable lines 33 and 34 in `Makefile` if the target is `deps-ubuntu`.

No target guessing is necessary. There's a third option (illustrated by the state of my PR before I had rebased it on here), which is better: Checking sem availability only when you actually need it. See current #145

2020-08-19 15:26 UTC, stweil commented on Makefile
> +$(if $(shell which sem),sem --fg --id --nn ocrd_all_git ,$(error "Please install GNU parallel"))
I would not call a test for `help` or `deps-ubuntu` target guessing, and we need that code for the `WGET` check, too (running make on Ubuntu with neither wget nor curl installed will currently always fail). So that's not wasted code. Therefore I decided against your alternative solution.

2020-08-19 17:26 UTC, bertsky commented on Makefile
> +$(if $(shell which sem),sem --fg --id --nn ocrd_all_git ,$(error "Please install GNU parallel"))
> I would not call a test for `help` or `deps-ubuntu` target guessing

Look, we want to look at the `sem` business this once, and then forget about it. As soon as other targets appear, which are legitimate before doing `deps-ubuntu` (or similar), or if we make something dependent on them, then these will have to be included in your list. Hence _guessing_.

> and we need that code for the `WGET` check, too

oh, right – I didn't notice that before. I'll add a fix to #145 for that along the same lines.

2020-08-20 09:36 UTC, stweil commented
This PR can be closed. Some of the commits are merged now, others will be replaced by PR #145.

2020-08-20 09:36 UTC, closed without merging