make check: check for parallel/wget/curl, fix #157
OCR-D/ocrd_all pull request #158
Opened 2020-08-20 13:38 UTC by kba

2020-08-20 13:48 UTC, stweil commented on Makefile
> +	@sem --version >/dev/null && echo "ok - parallel installed"
Then an error would be reported like this:

/bin/sh: 1: sem: not found

```suggestion
.PHONY: all modules check clean help show always-update

check:
	@sem --version >/dev/null 2>&1 || echo "error - please install GNU parallel"
```

2020-08-20 13:50 UTC, stweil commented on Makefile
> +	@sem --version >/dev/null && echo "ok - parallel installed"
I have no strong opinion regarding the success message, so `ok - parallel installed` could be added for the success case if desired.

2020-08-20 13:50 UTC, bertsky requested changes
I don't see the point. You already get appropriate error messages now when one of these tools is missing. No need to duplicate that under a new target. It will only confuse users. Other missing dependencies will produce errors when due, respectively.

2020-08-20 13:51 UTC, stweil commented on Makefile
> +	@{ wget --version || curl --version; } > /dev/null && echo "ok - wget/curl installed"
As we already have hard dependencies on `wget`, cleaning the current code would be reasonable - no need to support `curl` as well.

2020-08-20 14:01 UTC, stweil requested changes
Error messages should be added / improved, and instead of checking for curl or wget, a check for wget only would be better.

2020-08-20 14:12 UTC, kba commented on Makefile
> +	@{ wget --version || curl --version; } > /dev/null && echo "ok - wget/curl installed"
> I don't see the point. You already get appropriate error messages now when one of these tools is missing. No need to duplicate that under a new target. It will only confuse users. Other missing dependencies will produce errors when due, respectively.

I see this more as a documentation feature. If users do encounter problems, you could ask them: "What does `make check` say?" to quickly exclude missing dependencies. I'd say that is easier than capturing `make all` output and spot the error.

2020-08-20 14:14 UTC, kba commented on Makefile
> +	@{ wget --version || curl --version; } > /dev/null && echo "ok - wget/curl installed"
`> As we already have hard dependencies on `wget`, cleaning the current code would be reasonable - no need to support `curl` as well.

Since the `$(WGET)` macro checks `wget --version`, then `curl --version`, `make check` should also check in that order. The `||` should stop early if wget is available and test whether curl is available only if wget isn't.

2020-08-20 14:22 UTC, bertsky commented on Makefile
> +	@{ wget --version || curl --version; } > /dev/null && echo "ok - wget/curl installed"
> I see this more as a documentation feature. If users do encounter problems, you could ask them: "What does `make check` say?" to quickly exclude missing dependencies. I'd say that is easier than capturing `make all` output and spot the error.

What do you gain? – Nothing. Whether wget and parallel is missing is already reported by `make all` – at the very bottom (unless running parallel and for the first time).

What do you loose? – All the other possible sources of error. You'll usually have to ask for `make all` output anyway.

2020-08-20 14:30 UTC, stweil commented on Makefile
> +	@{ wget --version || curl --version; } > /dev/null && echo "ok - wget/curl installed"
Cleaning the `WGET` macro to only use `wget`is a separate task which can be done before or after this PR (but please in a separate PR). I just wanted to say that there is no need to support `curl` here and to remove that later again.

`make deps-ubuntu` installs `wget`.

2020-08-24 13:09 UTC, cneud commented
Just to note that ``curl`` is required for the [OCR-D Research Data Repository](https://ocr-d.de/en/setup#testing-the-installation-1) and since this is included with [taverna_workflow](https://github.com/OCR-D/taverna_workflow), users of that will see their workflows fail when ``curl`` is not installed by ``ocrd_all``.

2020-08-29 21:41 UTC, stweil commented
> Just to note that `curl` is required for the [OCR-D Research Data Repository](https://ocr-d.de/en/setup#testing-the-installation-1) and since this is included with [taverna_workflow](https://github.com/OCR-D/taverna_workflow), users of that will see their workflows fail when `curl` is not installed by `ocrd_all`.

`make deps-ubuntu` already installs `wget`. Should it also install `curl` then?

As far as I remember, a default installation of Ubuntu already includes `curl`, so most users will have it. For those who install a minimal Ubuntu adding `curl` to `CUSTOM_DEPS` might be a good idea.

2022-02-02 10:49 UTC, closed without merging