Make sure that pip always gets upgraded
OCR-D/ocrd_all pull request #211
Opened 2020-10-14 20:14 UTC by stweil

It was not upgraded for an existing venv.

Signed-off-by: Stefan Weil <sw@weilnetz.de>

2020-10-14 20:32 UTC, bertsky requested changes
Why not. But I wonder what your use-case is. We never needed to update from the old 9-something default until recently. Does this have to do with the new dependency resolver that will arrive by default soon?

2020-10-14 20:32 UTC, bertsky commented on Makefile
> +$(VIRTUAL_ENV)/bin/pip3: $(ACTIVATE_VENV)
```suggestion
$(VIRTUAL_ENV)/bin/$(PIP): $(ACTIVATE_VENV)
```

2020-10-14 20:32 UTC, bertsky commented on Makefile
> +$(OCRD_EXECUTABLES) $(BIN)/wheel: | $(VIRTUAL_ENV)/bin/pip3
```suggestion
$(OCRD_EXECUTABLES) $(BIN)/wheel: | $(VIRTUAL_ENV)/bin/$(PIP)
```

2020-10-14 20:36 UTC, stweil commented on Makefile
> +$(VIRTUAL_ENV)/bin/pip3: $(ACTIVATE_VENV)
That would not work if `PIP` includes a path prefix.

2020-10-14 20:41 UTC, bertsky commented on Makefile
> +$(VIRTUAL_ENV)/bin/pip3: $(ACTIVATE_VENV)
It was never intended or documented that way. The README and help texts all state `name of the ... binary`, to allow differentiating between different Python versions.

_Not_ respecting that variable here would break those existing use cases.

2020-10-14 20:41 UTC, stweil commented
> We never needed to update from the old 9-something default until recently.

Maybe most builds did not use an existing venv but created the venv? The Makefile already upgraded pip when it created a new venv.

2020-10-14 20:49 UTC, stweil commented on Makefile
> +$(VIRTUAL_ENV)/bin/pip3: $(ACTIVATE_VENV)
A virtual environment does not provide different Python versions, and as far as I know it will always have a `pip3` executable. Which use cases exist which would fail? I never have set `PIP` manually in any of my builds.

2020-10-14 21:32 UTC, bertsky commented
> > We never needed to update from the old 9-something default until recently.
> 
> Maybe most builds did not use an existing venv but created the venv? The Makefile already upgraded pip when it created a new venv.

No, creating a venv does **not** update pip automatically. We only noticed this when the old default version (it's `9.0.1` under Ubuntu 18.04) both pre-built wheels in the `manylinux2014` format and fallback installation from source distributions using `pyproject.toml` stopped working.

2020-10-15 05:52 UTC, stweil commented
> No, creating a venv does not update pip automatically.

The current Makefile creates the venv in line 141. Line 142 updates pip. I don't understand your no.

2020-10-15 06:18 UTC, bertsky commented
> > > We never needed to update from the old 9-something default until recently.
> > 
> > No, creating a venv does not update pip automatically.
> 
> The current Makefile creates the venv in line 141. Line 142 updates pip. I don't understand your no.

You are taking this out of context. The question remains: what do we need this change for in the first place?

2020-10-15 08:01 UTC, stweil commented
> The question remains: what do we need this change for in the first place?

See the commit message: pip was not upgraded for an existing venv. So for example this sequence would run with an old version of pip and possibly fail:

    python3.7 -m venv myvenv
    source myvenv/bin/activate
    make all

2020-10-15 09:48 UTC, kba commented on Makefile
> +$(VIRTUAL_ENV)/bin/pip3: $(ACTIVATE_VENV)
I agree that this is somewhat academical but you might want to ensure it's the pip for the right minor version of Python, e.g. `make all PIP=pip3.7`.

Be that as it may, it's still sensible to adhere to the `$(PIP)` scheme throughout.

2020-10-15 09:58 UTC, stweil commented on Makefile
> +$(VIRTUAL_ENV)/bin/pip3: $(ACTIVATE_VENV)
What about removing the `PIP` macro? I simply cannot imagine a real use case, as we always use virtual Python environments. I suggest to replace `$(PIP)` by `pip3` or even by `pip` because that avoids unused complexity.

2020-10-15 09:59 UTC, stweil commented on Makefile
> +$(VIRTUAL_ENV)/bin/pip3: $(ACTIVATE_VENV)
Or do we have submodules which use the exported `PIP`?

2020-10-15 10:15 UTC, stweil commented on Makefile
> +$(VIRTUAL_ENV)/bin/pip3: $(ACTIVATE_VENV)
@kba, `make all PIP=pip3.7` would work as expected, because the pip upgrade replaces `pip`, `pip3` and `pip3.7`.

2020-10-15 10:47 UTC, kba commented on Makefile
> +$(VIRTUAL_ENV)/bin/pip3: $(ACTIVATE_VENV)
When we started OCR-D phase II we had to support Python 2.7, hence you'll find PIP and PYTHON parameterizable in most of the Makefiles I originally set up.

I agree that we can revisit that design choice. But a pull request should do one thing and while simplifying unused complexity is a good idea per se, we should make sure it is actually unused.

2020-10-15 11:14 UTC, merged