make install-models: delegate to ocrd resmgr
OCR-D/ocrd_all pull request #234
Opened 2021-01-18 12:23 UTC by kba

Once OCR-D/core#559 is merged.

2021-01-22 13:19 UTC, bertsky requested changes
I recommend a more radical change: Instead of unconditionally delegating `install-models` to `install-models-ocropus`, `install-models-calamari` etc, we should make these subtargets depend on whether the respective module is in the currently active `OCRD_MODULES`, and encapsulate each such rule near the other rules for the modules. 

Thus, instead of …
```make
ifneq ($(findstring ocrd_cis, $(OCRD_MODULES)),)
OCRD_EXECUTABLES += $(OCRD_CIS)
...
```

…we would have…
```make
ifneq ($(findstring ocrd_cis, $(OCRD_MODULES)),)
install-models: install-models-cis
install-models-cis: $(BIN)/ocrd
	. $(ACTIVATE_VENV) && ocrd resmgr download ocrd-cis-ocropy-recognize '*'
OCRD_EXECUTABLES += $(OCRD_CIS)
...
```

Also, we still need to adapt `Dockerfile`:
```Dockerfile
ENV XDG_DATA_HOME /usr/local/share
VOLUME $XDG_DATA_HOME/ocrd-resources
```

(perhaps also `HOME` itself)

2021-01-25 11:39 UTC, kba commented
Having thought about it some more, I agree that `install-models-*` should depend on `OCRD_MODULES` to ensure that only the models are installed for those processors the user requested (by having it in `OCRD_MODULES`)

2021-01-25 11:48 UTC, kba commented
> we should make these subtargets depend on whether the respective module is in the currently active OCRD_MODULES

fb4ee26

> Also, we still need to adapt Dockerfile:

2fdce0a

2021-01-25 12:16 UTC, bertsky approved these changes
Splendid – thanks!

Perhaps we could offer more of these `install-models-*` rules in order to allow a quick installation without studying all processors and available models? (Currently, I would still have to `ocrd resmgr download PROCESSOR '*'` selectively for each processor I might want to use.)

2021-01-25 12:16 UTC, bertsky commented on Makefile
> +	. $(ACTIVATE_VENV) && ocrd resmgr download ocrd-calamari-binarize '*'
Shouldn't that be…
```suggestion
	. $(ACTIVATE_VENV) && ocrd resmgr download ocrd-calamari-recognize '*'
```
…actually?

2021-01-25 16:38 UTC, kba commented
> Perhaps we could offer more of these `install-models-*`

384ee6d I added targets for all projects that we have in core's `resource_list.yml`.

You could always do the installation and then `ocrd resmgr download '*'` to download all models at once later on.

2021-01-30 14:35 UTC, merged