:package: v2021-02-27
OCR-D/ocrd_all pull request #242
Opened 2021-02-26 16:30 UTC by kba

@stweil Can/should we update tesseract to master?

2021-02-26 16:32 UTC, stweil commented
Yes, I think so. See also https://github.com/tesseract-ocr/tesseract/pull/3141#issuecomment-785896647.

2021-02-26 17:30 UTC, kba commented
> Yes, I think so. See also [tesseract-ocr/tesseract#3141 (comment)](https://github.com/tesseract-ocr/tesseract/pull/3141#issuecomment-785896647).

Building tesserocr [failed](https://app.circleci.com/pipelines/github/OCR-D/ocrd_all/501/workflows/6ae977f3-2de7-49fa-9bea-21cf04d226b1/jobs/495) with

```
tesserocr.cpp:681:10: fatal error: tesseract/genericvector.h: No such file or directory
   #include "tesseract/genericvector.h"
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~
```

@stweil Since https://github.com/sirfz/tesserocr/pull/242 is merged but no new release yet available, we'll have to change to using tesserocr GH master instead of PyPI for the time being, correct?

2021-02-26 17:55 UTC, stweil commented
As far as I know we use `tesserocr` submodule (not PyPI), but the submodule needs of course an update if it does not include that commit.

2021-02-26 17:59 UTC, stweil commented
@kba, I just fixed a major issue for Tesseract training. Maybe you want an update to latest git master to get that fix, too.

2021-02-26 18:44 UTC, bertsky requested changes
Please update ocrd_segment once more. (Contains a fallback in case there's no ReadingOrder.)

2021-02-26 18:44 UTC, bertsky commented on CHANGELOG.md
> +  > * 🚧 Replace Travis with CircleCI
Is this repetition of log messages something we could suppress in our script for the aggregated changelog?

2021-02-27 16:09 UTC, kba commented on CHANGELOG.md
> +  > * 🚧 Replace Travis with CircleCI
We could pipe the output through `uniq`.

2021-02-27 16:15 UTC, kba commented on CHANGELOG.md
> +  > * 🚧 Replace Travis with CircleCI
done 6229c7d

2021-02-27 16:58 UTC, merged