make Python 3.8 work
OCR-D/ocrd_all pull request #289
Opened 2022-02-19 11:48 UTC by bertsky

Depends on https://github.com/OCR-D/ocrd_anybaseocr/pull/89 (which in turn depends on https://github.com/OCR-D/ocropy/pull/2).

2022-02-19 13:02 UTC, bertsky commented
CI failure: the same idiotic reason as in the [other PRs](https://github.com/OCR-D/ocrd_all/pull/288#issuecomment-1043619930). Anyone has a solution?

2022-03-04 16:19 UTC, kba commented on Makefile
> +	pushd $$name && for path in $$name*; do mv $$path $${path/$$name/$$newname}; done && popd && \
wow

2022-03-04 16:20 UTC, kba approved these changes

2022-03-04 16:26 UTC, stweil commented on Makefile
> +	pushd $$name && for path in $$name*; do mv $$path $${path/$$name/$$newname}; done && popd && \
Do you expect that this will work for any architecture? I am afraid that it is limited to x86_64.

2022-03-04 17:14 UTC, stweil requested changes
Building with Python 3.7 no longer works for me after I merged this PR. It fails for the `headless-tf1` parts.

I also tried Python 3.9 (the default for Debian stable) which failed similarly.

2022-03-04 23:10 UTC, bertsky commented
> Building with Python 3.7 no longer works for me after I merged this PR. It fails for the `headless-tf1` parts.

Then please share the error log so we can resolve this quickly.

> I also tried Python 3.9 (the default for Debian stable) which failed similarly.

Yeah sure, but that's true for master, too. (I am not claiming I can solve **all problems at once**.)

2022-03-04 23:13 UTC, bertsky commented
CI failure:
```
. /usr/local/sub-venv/headless-torch14/bin/activate && sem --will-cite --fg --id ocrd_all_pip/usr/local/sub-venv/headless-torch14 pip3 install --upgrade pip setuptools
Exception:
Traceback (most recent call last):
  File "/usr/local/sub-venv/headless-torch14/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/sub-venv/headless-torch14/lib/python3.6/site-packages/pip/commands/install.py", line 290, in run
    with self._build_session(options) as session:
  File "/usr/local/sub-venv/headless-torch14/lib/python3.6/site-packages/pip/basecommand.py", line 69, in _build_session
    if options.cache_dir else None
  File "/usr/lib/python3.6/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not int
```
I remember seeing this before, and solving be replacing/removing the pip cache dir.

2022-03-05 09:15 UTC, stweil commented
> Then please share the error log so we can resolve this quickly.

See https://github.com/stweil/ocrd_all/actions.

Before merging this pull request, Python 3.6 and Python 3.7 work fine while Python 3.8 fails as expected (https://github.com/stweil/ocrd_all/actions/runs/1937666710).

After merging this pull request, Python 3.7 fails (https://github.com/stweil/ocrd_all/actions/runs/1937673668).

2022-03-07 13:46 UTC, bertsky commented
> After merging this pull request, Python 3.6 and Python 3.8 work, but Python 3.7 fails (https://github.com/stweil/ocrd_all/actions/runs/1937673668).

Thanks! I updated the workaround to only activate in the case of Python 3.8. (AFAICS, on 3.7 this is not necessary, and we simply do not newer versions anyway.)

2022-03-07 13:48 UTC, bertsky commented
> I remember seeing this before, and solving be replacing/removing the pip cache dir.

Which is strange, because you would expect the CI container to start without a cache, and without `-j` there should be no outside interference/race against the cache...

Current CI failure is the 1h timeout again. :disappointed:

2022-03-16 19:56 UTC, stweil commented on Makefile
> +	pushd $$name && for path in $$name*; do mv $$path $${path/$$name/$$newname}; done && popd && \
Ping @bertsky.

2022-03-16 20:00 UTC, stweil requested changes
It looks like handling of non Intel architectures is still missing.

2022-03-16 20:06 UTC, stweil commented
@bertsky, I think we can address the unhandled target architectures later and apply the pull request.

Maybe you can change the code which checks the Python version and introduce a new macro `PYTHON_VERSION` which will be needed for other rules, too: https://github.com/stweil/ocrd_all/commit/663544450eb9d51e96aea8619dcb94149637e7e7

2022-03-16 22:09 UTC, bertsky commented on Makefile
> +	pushd $$name && for path in $$name*; do mv $$path $${path/$$name/$$newname}; done && popd && \
> Do you expect that this will work for any architecture? I am afraid that it is limited to x86_64.

AFAIK Nvidia only ships wheels for Linux on x86_64. (See [release notes](https://docs.nvidia.com/deeplearning/frameworks/tensorflow-wheel-release-notes/tf-wheel-rel.html). Since they seem to be the only project willing to continue to support TF 1, that's as good as it gets.)

2022-03-16 22:17 UTC, bertsky commented
@stweil,
> I think we can address the unhandled target architectures later and apply the pull request.

Definitely. When and if...

> Maybe you can change the code which checks the Python version and introduce a new macro `PYTHON_VERSION` which will be needed for other rules, too: [stweil@6635444](https://github.com/stweil/ocrd_all/commit/663544450eb9d51e96aea8619dcb94149637e7e7)

There's a [recipe here](https://github.com/bertsky/ocrd_all/commit/c376a6bd79a092efe87a1286965f52f3a0b2ea3a) already which detects the major version. IIUC you want to expose that as a make variable for other rules as well. How is that related to this PR?

2022-03-16 22:23 UTC, bertsky commented
CI: 033b5dd does the trick for now. We should revisit the problems related to use of `make -j` later, but for now the time is just enough for the 1h+1m limit. (We can still disable the lengthy `docker image save` and artifact uploading later, if we exceed the limit but have not tackled the parallel build issues yet.)

Thus, ready for merging.

2022-03-18 12:33 UTC, bertsky commented
Now runs into the CircleCI timeout again. I'll disable saving artifacts.

2022-03-18 14:35 UTC, merged

2022-03-30 18:28 UTC, stweil commented on Makefile
> +endif
Why was this block added? I don't think that it is a good idea to install a Python package from PPA just because the user added `PYTHON=python3.7` to the build options. It can either overwrite an existing installation or install an unneeded 2nd Python installation.

I noticed these instructions while building a Docker image with GitLab actions which already provides any desired Python version.

2022-03-30 18:50 UTC, bertsky commented on Makefile
> +endif
Because our current reference platform, i.e. the one targeted by `deps-ubuntu`, is still Ubuntu 18.04. And that uses 3.6 by default for python3, and needs PPAs for more recent versions. (Same with our ocrd_tesserocr recipe.)

I agree it's not a good pattern, but we need some kind of dual version support during the grace period between Ubuntu 18 and 20 (Python 3.6 and 3.8). Think of it as something we can drop as soon as the shift to 20 is complete. (And after that we should find better mechanisms to encapsulate system dependencies.)

I think the natural way to avoid interference with tailored environments like CI is to _not_ set `PYTHON` there, but instead make it that environment's default version.

2022-03-31 03:41 UTC, stweil commented on Makefile
> +endif
18.04 does not need PPA for Python 3.7: https://packages.ubuntu.com/search?keywords=python3.7. And I don't think that the installation of Python should be part of the Makefile rules. Let it fail if someone says `make all PYTHON=python3.7` without providing that version.