Add new macro PYTHON_VERSION
OCR-D/ocrd_all pull request #297
Opened 2022-03-16 21:37 UTC by stweil

It is used for special handling of several versions of Python,
here to disable ocrd_kraken with Python 3.10.

Signed-off-by: Stefan Weil <sw@weilnetz.de>

2022-03-16 21:38 UTC, stweil commented
This is an extract from PR #295 and can be reused in PR #289.

2022-03-16 21:46 UTC, stweil commented
We could use `PYTHON_VERSION` also as a hack to disable submodules which require old Tensorflow versions for newer versions of Python which don't provide those versions. That's much faster than the (cleaner) solution to check whether the required Tensorflow versions are available.

2022-03-18 10:05 UTC, kba approved these changes

2022-03-18 10:40 UTC, bertsky requested changes
> This is an extract from PR https://github.com/OCR-D/ocrd_all/pull/295 and can be reused in PR https://github.com/OCR-D/ocrd_all/pull/289.

#289 already came first with that recipe BTW.

2022-03-18 10:40 UTC, bertsky commented on Makefile
> +endif
This defies several layers of module selection mechanisms that are already in place.

If the user chose to install the ocrd_kraken module, then it is wrong to silently ignore it.

The proper way to remove a module for a certain Python version _by default_ would be to include it in `DISABLED_MODULES`.

2022-03-18 11:21 UTC, kba commented on Makefile
> +endif
So

```make
DISABLED_MODULES ?= cor-asv-fst opencv-python ocrd_ocropy
ifeq ($(PYTHON_VERSION),3.10)                            
# Python 3.10.x does not work with current kraken.       
DISABLED_MODULES += ocrd_kraken                          
endif                                                    
```

would still allow overriding with `OCRD_MODULES` but disables it by default for 3.10?

2022-03-18 11:36 UTC, bertsky commented on Makefile
> +endif
Not quite. That would still override any explicit user (or Docker) setting for `DISABLED_MODULES`. But we only want to override the actual default:

```make
ifeq ($(PYTHON_VERSION),3.10)
# Python 3.10.x does not work with current kraken.
DISABLED_MODULES ?= cor-asv-fst opencv-python ocrd_ocropy ocrd_kraken
else
DISABLED_MODULES ?= cor-asv-fst opencv-python ocrd_ocropy
endif
```

2022-03-18 12:00 UTC, stweil commented on Makefile
> +endif
My patch disables `ocrd_kraken` unconditionally for Python 3.10 (which is necessary because that combination does not work). The proposed alternatives don't do that. Therefore I don't think they are equally good or even better.

2022-03-18 12:02 UTC, stweil commented on Makefile
> +endif
We could discuss how to handle submodules which are disabled automatically because they don't work. Instead of silently disabling them, there could be a report (for example at the end of the build process) about those disabled submodules.

2022-03-18 12:07 UTC, bertsky commented on Makefile
> +endif
> My patch disables `ocrd_kraken` unconditionally for Python 3.10

exactly.

> (which is necessary because that combination does not work)

thus, let it fail (loudly)!

> Therefore I don't think they are equally good or even better.

As argued above, they are better (you did not address the arguments).

> We could discuss how to handle submodules which are disabled automatically because they don't work. Instead of silently disabling them, there could be a report (for example at the end of the build process) about those disabled submodules.

That would only complicate matters further, and goes against the user expectations of running `make`. If a module does not work in your environment (whatever the cause or kind), then the simplest and uniform answer is that module's build failing (while others can continue if running with `-k`). Also, the build is incremental, so as soon as the user fixed it (by disabling the module or installing by hand), one can continue.

2022-03-18 12:13 UTC, stweil commented on Makefile
> +DISABLED_MODULES ?= cor-asv-fst opencv-python ocrd_ocropy ocrd_kraken
That pattern no longer works as soon as I want to disable other submodules for other Python versions!

2022-03-18 12:30 UTC, bertsky commented on Makefile
> +DISABLED_MODULES ?= cor-asv-fst opencv-python ocrd_ocropy ocrd_kraken
> That pattern no longer works as soon as I want to disable other submodules for other Python versions!

If and when that happens, `make` still offers plenty of other syntax to achieve the same thing.

2022-03-18 12:38 UTC, stweil commented on Makefile
> +DISABLED_MODULES ?= cor-asv-fst opencv-python ocrd_ocropy ocrd_kraken
Then I need your help. How would that look like?

2022-03-18 12:46 UTC, bertsky commented on Makefile
> +DISABLED_MODULES ?= cor-asv-fst opencv-python ocrd_ocropy ocrd_kraken
For example, something along the lines of:
```make
DISABLED_MODULES ?= $(DEFAULT_DISABLED_MODULES)
DEFAULT_DISABLED_MODULES = cor-asv-fst opencv-python ocrd_ocropy
ifeq ($(PYTHON_VERSION),3.10)
# Python 3.10.x does not work with current kraken.
DISABLED_MODULES += ocrd_kraken
endif
ifeq (...)
DISABLED_MODULES += ...
endif
```

2022-03-18 12:50 UTC, stweil commented on Makefile
> +DISABLED_MODULES ?= cor-asv-fst opencv-python ocrd_ocropy ocrd_kraken
That would change the user interface, right? Instead of providing `DISABLED_MODULES` they would have to use `DEFAULT_DISABLED_MODULES`. Of course all documentation would require an update, too.

Would that be acceptable and better than my original solution?

2022-03-18 12:55 UTC, bertsky commented on Makefile
> +DISABLED_MODULES ?= cor-asv-fst opencv-python ocrd_ocropy ocrd_kraken
No, it would not. The user does not need to know anything about `DEFAULT_DISABLED_MODULES`. In fact, that is the whole point (to have a dynamic default, but allowing explicit user-defined opt-outs as already documented).

2022-03-18 13:19 UTC, bertsky approved these changes

2022-03-18 13:45 UTC, merged