update 2022-06-03
OCR-D/ocrd_all pull request #326
Opened 2022-06-02 17:45 UTC by kba

2022-06-02 18:34 UTC, stweil requested changes
Fine for me, but I missed the changelog for ocrd_all itself.

2022-06-03 07:59 UTC, kba commented
Good point, I'll amend the CHANGELOG.

2022-06-03 10:33 UTC, bertsky approved these changes
LGTM

2022-06-03 11:08 UTC, kba commented
https://github.com/OCR-D/ocrd_all/pull/326/commits/1cb4a6057a2aead5ed9da52b927cd59db4f24281 added CHANGELOG for ocrd_all itself.

2022-06-03 11:14 UTC, stweil approved these changes

2022-06-03 11:23 UTC, stweil commented on CHANGELOG.md
> +## [v2022-06-02](https://github.com/OCR-D/ocrd_all/releases/v2022-06-02)
@kba, maybe update the date here.

2022-06-03 11:55 UTC, kba commented on CHANGELOG.md
> +## [v2022-06-02](https://github.com/OCR-D/ocrd_all/releases/v2022-06-02)
https://github.com/OCR-D/ocrd_all/pull/326/commits/4f070d4140702e3fbf6e4720b0864d63e94aa5f4 done

2022-06-03 13:57 UTC, merged